package com.pumpapp.pumpapp.enums

enum class TipoAccesorio {
    VALVULA_DE_BOLA,
    VALVULA_DE_ANGULO,
    VALVULA_DE_GLOBO,
    CODO_NOVENTA,
    CODO_CUARENTA_Y_CINCO,
    VUELTA_RETORNO,
    TE_FLUJO_NORMAL,
    TE_FLUJO_INVERTIDO,
    CABEZAL_LLAVE_DE_PASO,
    CABEZAL_VALVULA_PRESION;
}